// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int32              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	UserName     string             `json:"user_name"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Bio          string             `json:"bio"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
